/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { alternative_identifier } from './alternative_identifier';
import type { carrier_code } from './carrier_code';
import type { date_type } from './date_type';
import type { date_time } from './date_time';
import type { delivery_confirmation } from './delivery_confirmation';
import type { display_scheme } from './display_scheme';
import type { image_id } from './image_id';
import type { label_charge_event } from './label_charge_event';
import type { label_download } from './label_download';
import type { label_download_type } from './label_download_type';
import type { label_format } from './label_format';
import type { label_layout } from './label_layout';
import type { label_package } from './label_package';
import type { label_status } from './label_status';
import type { link } from './link';
import type { monetary_value } from './monetary_value';
import type { optional_link } from './optional_link';
import type { package_code } from './package_code';
import type { paperless_download } from './paperless_download';
import type { se_id } from './se_id';
import type { service_code } from './service_code';
import type { shipment } from './shipment';
import type { shipping_address_to } from './shipping_address_to';
import type { tracking_status } from './tracking_status';
import type { validate_address } from './validate_address';
/**
 * A label represents the physical sticker that you affix to a package to ship it.  ShipStation makes it easy for you to [create labels] and then download them in PDF, PNG, or ZPL format so you can print them.
 *
 */
export type label = {
    /**
     * A string that uniquely identifies the label. This ID is generated by ShipStation when the label is created.
     *
     */
    readonly label_id?: se_id;
    readonly status?: label_status;
    /**
     * The shipment that this label is for.  ShipStation  can create a shipment for you automatically when you [create a label], or you can [create your own shipment] and then [use it to print a label]
     *
     */
    readonly shipment_id?: se_id;
    /**
     * A unique user-defined key to identify a shipment.  This can be used to retrieve the shipment.
     *
     * > **Warning:** The `external_shipment_id` is limited to 50 characters. Any additional characters will be truncated.
     *
     */
    readonly external_shipment_id?: string;
    /**
     * ID that the Order Source assigned
     */
    readonly external_order_id?: string;
    /**
     * The shipment information used to generate the label
     */
    shipment?: shipment;
    /**
     * The date that the package was (or will be) shippped.  ShipStation will take the day of week into consideration. For example, if the carrier does not operate on Sundays, then a package that would have shipped on Sunday will ship on Monday instead.
     *
     */
    readonly ship_date?: date_type;
    /**
     * The date and time that the label was created in ShipStation .
     */
    readonly created_at?: date_time;
    /**
     * The cost of shipping, delivery confirmation, and other carrier charges.  This amount **does not** include insurance costs.
     *
     */
    readonly shipment_cost?: monetary_value;
    /**
     * The insurance cost for this package.  Add this to the `shipment_cost` field to get the total cost.
     *
     */
    readonly insurance_cost?: monetary_value;
    /**
     * The total shipping cost for the specified comparison_rate_type.
     *
     */
    readonly requested_comparison_amount?: monetary_value;
    /**
     * The tracking number for the package. Tracking number formats vary across carriers.
     */
    readonly tracking_number?: string;
    /**
     * Indicates whether this is a return label.  You may also want to set the `rma_number` so you know what is being returned.
     *
     */
    is_return_label?: boolean;
    /**
     * An optional Return Merchandise Authorization number.  This field is useful for return labels.  You can set it to any string value.
     *
     */
    rma_number?: string;
    /**
     * Indicates whether this is an international shipment.  That is, the originating country and destination country are different.
     *
     */
    readonly is_international?: boolean;
    /**
     * If this label was created as part of a [batch], then this is the unique ID of that batch.
     *
     */
    readonly batch_id?: se_id;
    /**
     * The unique ID of the [carrier account] that was used to create this label
     *
     */
    readonly carrier_id?: se_id;
    /**
     * The label charge event.
     *
     */
    charge_event?: label_charge_event;
    /**
     * The `label_id` of the original (outgoing) label that the return label is for. This associates the two labels together, which is
     * required by some carriers.
     *
     */
    outbound_label_id?: se_id;
    /**
     * The [carrier service] used to ship the package, such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, etc.
     *
     */
    readonly service_code?: service_code;
    /**
     * Indicate if this label is being used only for testing purposes. If true, then no charge will be added to your account.
     * @deprecated
     */
    test_label?: boolean;
    /**
     * The [package type], such as `thick_envelope`, `small_flat_rate_box`, `large_package`, etc.  The code `package` indicates a custom or unknown package type.
     *
     */
    readonly package_code?: package_code;
    validate_address?: validate_address;
    /**
     * Indicates whether the label has been [voided]
     *
     */
    readonly voided?: boolean;
    /**
     * The date and time that the label was [voided] , or `null` if the label has not been voided
     *
     */
    readonly voided_at?: date_time;
    label_download_type?: label_download_type;
    /**
     * The file format that you want the label to be in.  We recommend `pdf` format because it is supported by all carriers, whereas some carriers do not support the `png` or `zpl` formats.
     *
     */
    label_format?: label_format;
    /**
     * The display format that the label should be shown in.
     */
    display_scheme?: display_scheme;
    /**
     * The layout (size) that you want the label to be in.  The `label_format` determines which sizes are allowed.  `4x6` is supported for all label formats, whereas `letter` (8.5" x 11") is only supported for `pdf` format.
     *
     */
    label_layout?: label_layout;
    /**
     * Indicates whether the shipment is trackable, in which case the `tracking_status` field will reflect the current status and each package will have a `tracking_number`.
     *
     */
    readonly trackable?: boolean;
    /**
     * The label image resource that was used to create a custom label image.
     */
    label_image_id?: image_id;
    /**
     * The [shipping carrier] who will ship the package, such as `fedex`, `dhl_express`, `stamps_com`, etc.
     *
     */
    readonly carrier_code?: carrier_code;
    /**
     * The type of delivery confirmation that is required for this shipment.
     */
    readonly confirmation?: delivery_confirmation;
    /**
     * The current status of the package, such as `in_transit` or `delivered`
     */
    readonly tracking_status?: tracking_status;
    readonly label_download?: label_download;
    /**
     * The link to download the customs form (a.k.a. commercial invoice) for this shipment, if any.  Forms are in PDF format. This field is null if the shipment does not require a customs form, or if the carrier does not support it.
     *
     */
    readonly form_download?: link;
    /**
     * The QR code download for the package
     */
    readonly qr_code_download?: optional_link;
    /**
     * The paperless details which may contain elements like `href`, `instructions` and `handoff_code`.
     *
     */
    readonly paperless_download?: paperless_download;
    /**
     * The link to submit an insurance claim for the shipment.  This field is null if the shipment is not insured or if the insurance provider does not support online claim submission.
     *
     */
    readonly insurance_claim?: link;
    /**
     * The label's package(s).
     *
     * > **Note:** Some carriers only allow one package per label.  If you attempt to create a multi-package label for a carrier that doesn't allow it, an error will be returned.
     *
     */
    readonly packages?: Array<(label_package & {
        /**
         * Alternative identifiers associated with this package.
         *
         */
        readonly alternative_identifiers?: Array<alternative_identifier>;
    })>;
    /**
     * Additional information some carriers may provide by which to identify a given label in their system.
     *
     */
    readonly alternative_identifiers?: Array<alternative_identifier>;
    readonly rate_details?: Array<{
        rate_detail_type?: string;
        carrier_description?: string;
        carrier_billing_code?: string;
        carrier_memo?: string;
        amount?: monetary_value;
        billing_source?: string;
    }>;
    /**
     * The URL to track the package. This URL is provided by the carrier and is unique to the tracking number.
     *
     */
    readonly tracking_url?: string;
    /**
     * The recipient's mailing address
     */
    readonly ship_to?: shipping_address_to;
};

